train:
  _target_: datasets.vctk.BinauralVCTKTrain
  segment_length: 65536
  fs: 16000
  path: /shared/cycle1_biu_gannot_prj/datsets/vctk/VCTK-Corpus-0.92/wav16k
  speakers_discard: ["p280", "p315"]
  speakers_test: ["p351", "p360",]
  normalize: False
  #sigma_data: 0.05 #for normalization purposes
  #random seed
  seed: 0

test:
  _target_: datasets.vctk.BinauralVCTKTestPaired
  segment_length: 65536
  fs: 16000
  path: /shared/cycle1_biu_gannot_prj/datsets/vctk/VCTK-Corpus-0.92/wav16k
  rir_df_path: /shared/cycle1_biu_gannot_prj/datsets/hrtf_db/csvs/HRTF_train_VAE_wsj0_10k_mp_clean.csv
  speakers_discard: ["p280", "p315"]
  speakers_test: ["p226", "p287"]
  normalize: False
  num_examples: 16
  #random seed
  seed: 0
